CREATE TABLE goals (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       user_id BIGINT NOT NULL,
                       category_id BIGINT NOT NULL,
                       amount DECIMAL(19,2) NOT NULL,
                       month DATE NOT NULL,
                       type VARCHAR(50) NOT NULL,
                       FOREIGN KEY (user_id) REFERENCES users(id),
                       FOREIGN KEY (category_id) REFERENCES categories(id)
);